### ISSUE TITLE
Add More Badges

### ISSUE THREAD

**Issue by SamarAanand** [SamarAanand/A2Z-DSA#2]
It would be beneficial to add more badges or [Shields](https://shields.io/). Kindly help me with this issue.

![image](https://github.com/user-attachments/assets/a34ed622-4216-48b6-9152-f9a0cb4dabe0)

**Comment by yashksaini-coder** [comment]
Hi @SamarAanand Can you assign this issue to me. I am very familiar with these have used them before. 

You can check these repos for proof:- 
- ![image](https://github.com/user-attachments/assets/9e3ceb79-a7a8-40a8-b4e0-c22a8132a0ce)
- ![image](https://github.com/user-attachments/assets/9978d25a-6fd6-4c2b-9ec7-85d2f2a8518b)

**Comment by SamarAanand** [comment]
Okh I have assigned this issue to @yashksaini-coder Update the README with badges.
